-- ============================================
-- Billing Schedule (V2)
-- Pre-generated invoice timeline per contract
-- Drafts require human approval before Xero push
-- ============================================

CREATE TABLE billing_schedule (
    id                          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id                   UUID        NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    contract_id                 UUID        NOT NULL REFERENCES service_contracts(id) ON DELETE RESTRICT,
    billing_period_start        DATE        NOT NULL,
    billing_period_end          DATE        NOT NULL,
    billing_date                DATE        NOT NULL,
    invoice_number_in_season    SMALLINT    NOT NULL,
    total_invoices_in_season    SMALLINT    NOT NULL,
    planned_amount              NUMERIC(10,2),
    status                      VARCHAR(20) NOT NULL DEFAULT 'scheduled',
    invoice_draft_id            UUID,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_billing_schedule_status CHECK (status IN (
        'scheduled', 'draft', 'approved', 'skipped'
    ))
);

CREATE INDEX idx_billing_schedule_tenant_date ON billing_schedule(tenant_id, billing_date, status) WHERE status = 'scheduled';
CREATE UNIQUE INDEX idx_billing_schedule_contract_period ON billing_schedule(contract_id, billing_period_start);

CREATE TRIGGER billing_schedule_updated_at
    BEFORE UPDATE ON billing_schedule
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Invoice drafts generated by billing engine
CREATE TABLE invoice_drafts (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           UUID        NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
    customer_id         UUID        NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    contract_id         UUID        REFERENCES service_contracts(id) ON DELETE SET NULL,
    billing_schedule_id UUID        REFERENCES billing_schedule(id) ON DELETE SET NULL,
    draft_number        VARCHAR(20) NOT NULL,
    line_items          JSONB       NOT NULL DEFAULT '[]',
    subtotal            NUMERIC(10,2) NOT NULL DEFAULT 0,
    tax_rate            NUMERIC(5,4) NOT NULL DEFAULT 0,
    tax_amount          NUMERIC(10,2) NOT NULL DEFAULT 0,
    total_amount        NUMERIC(10,2) NOT NULL DEFAULT 0,
    description         TEXT,
    status              VARCHAR(20) NOT NULL DEFAULT 'pending_review',
    reviewed_by         UUID        REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at         TIMESTAMPTZ,
    approved_by         UUID        REFERENCES users(id) ON DELETE SET NULL,
    approved_at         TIMESTAMPTZ,
    pushed_to_xero      BOOLEAN     NOT NULL DEFAULT FALSE,
    xero_invoice_id     VARCHAR(255),
    invoice_id          UUID        REFERENCES invoices(id) ON DELETE SET NULL,
    rejection_reason    TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_invoice_draft_status CHECK (status IN (
        'pending_review', 'reviewed', 'approved', 'rejected', 'pushed_to_xero'
    ))
);

CREATE INDEX idx_invoice_drafts_tenant_status ON invoice_drafts(tenant_id, status) WHERE status IN ('pending_review', 'reviewed');
CREATE INDEX idx_invoice_drafts_customer ON invoice_drafts(customer_id, created_at DESC);
CREATE INDEX idx_invoice_drafts_contract ON invoice_drafts(contract_id) WHERE contract_id IS NOT NULL;

CREATE TRIGGER invoice_drafts_updated_at
    BEFORE UPDATE ON invoice_drafts
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
